import Footer from '@sections/footer'
import Header from '@sections/header'
import '@styles/global.scss'
import { Inter } from 'next/font/google'  

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pet Lodge USA of Boardman',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
