 
import Footer from '@sections/footer'
import Header from '@sections/header'
import '@styles/global.scss'
import { Inter } from 'next/font/google'     
const inter = Inter({ subsets: ['latin'] })

type PageType = { children: React.ReactNode }

export const metadata = {
  title: 'Pet Lodge USA of Boardman',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Pet Lodge USA of Boardman',
    description: 'Stay safe and be well! Kim, Scott, and all of us at Pet Lodge USA of Boardman.',
    images: '/icontrans.png',
    type: 'website'
  },
}

export default function RootLayout({ children, }:PageType ) {   
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  )
}
